/*
 * Whether plain char is signed is the target's choice, and the choice decides
 * this assertion: 200 does not fit a signed char, so on x86-64 x is -56 and on
 * riscv64 it is 200.
 *
 * The printed AST is byte-identical under gcc_x86_64 and
 * machdep_gcc_riscv64.yaml, measured with Frama-C 33.0. Only the machdep says
 * which program this is, so a proof here is a fact about one target.
 *
 * machdep_gcc_riscv64.yaml beside this file was generated by Frama-C 33.0's
 * make_machdep.py with riscv64-linux-gnu-gcc 13.3.0; no riscv machdep ships
 * with Frama-C 33.0.
 */
int widen(void)
{
    char c = (char) 200;
    int x = c;
    /*@ assert unsigned_char: x == 200; */
    return x;
}
